server:
  port: 8081
logging:
  config: classpath:log/logback.xml
# mybatis 配置
mybatis:
  #标注mybatis配置文件的位置
#  type-aliases-package: com.zjj.domain
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-location: classpath:mybatis.xml
spring:
  datasource:
    username: root
    password: root
    #url中database为对应的数据库名称
    url: jdbc:mysql://192.168.59.128:3306/mybatis_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



